# Generated by Django 5.2.6 on 2025-09-17 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_imageicon_delete_serviceinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='imageicon',
            field=models.FileField(blank=True, null=True, upload_to='services/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
