# Generated by Django 5.2.6 on 2025-09-19 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_imageicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mainpicture',
            field=models.FileField(blank=True, null=True, upload_to='pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='service',
            name='imageicon',
            field=models.FileField(blank=True, null=True, upload_to='pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])]),
        ),
    ]
