# Generated by Django 5.2.6 on 2025-09-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_mainpicture_alter_service_imageicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mainpicture',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
    ]
