# Generated by Django 5.2.6 on 2025-09-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_mainpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=100)),
                ('thequestion', models.TextField(max_length=10000)),
                ('theanswer', models.TextField(max_length=10000)),
            ],
        ),
    ]
