# Generated by Django 5.2.6 on 2025-09-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_name',
            new_name='name',
        ),
    ]
